server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://avin-db.ccxjc4qlbrep.ap-northeast-2.rds.amazonaws.com:6612/avin
    username: segeg
    password: dlwnsgk2!
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  security:
    user:
      name: admin
      password: admin
    oauth2:
      client:
        registration:
          github: 
            client-id: e6239cb309eaaba75d98
            client-secret: dd3626c9879e8f3455ee1596763c6bf7bcde4471
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
          facebook:
            client-name: facebook
            provider: facebook
            client-id: "763385107409058"
            client-secret: 18df9d730ed2cc59787d36f907e23f23
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            client-authentication-method: post
            scope:
              - email
              - public_profile
          google:
            client-id: 265824773318-4611kco6bphipavq193p22olukuko5cv.apps.googleusercontent.com
            client-secret: Bw9Rjkyhz84vRO3o-dKgpfux
            redirect-uri: "http://localhost:8080/oauth2/callback/google"
            scope:
              - email
              - profile
          kakao:
            authorization-grant-type: authorization_code
            client-id: 524d446c73e56b0e2bd64962695d5259
            client-secret: zJQlrzwyZyrAYt73KksvEOoK5nmnyGSF
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            provider: kakao
            client-authentication-method: post
            scope:
              - profile
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: post
            user-name-attribute: id
          facebook:
            authorization-uri: https://www.facebook.com/v4.0/dialog/oauth
            token-uri: https://graph.facebook.com/oauth/access_token
            user-name-attribute: id
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email
            user-info-authentication-method: post

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2